my_krzyzak21/blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostsFeed

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    # path('', views.PostListView.as_view(), name='post_list'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search')
]

my_krzyzak21/my_krzyzak21/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {
    'post': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name="base.html"), name="base"),
    # my pages
    path('blog/', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    # more pages
    path('404/', TemplateView.as_view(template_name="404.html"), name="404"),
    path('dashboard/', TemplateView.as_view(template_name="dashboard.html"), name="dashboard"),
    # to users
    path('account/', include('account.urls')),
    # to social
    path('social-auth/', include('social_django.urls', namespace='social')),
    # images
    path('images/', include('images.urls', namespace='images')),
    # to remove
    path('buttons/', TemplateView.as_view(template_name="to_remove/buttons.html"), name="buttons"),
    path('cards/', TemplateView.as_view(template_name="to_remove/cards.html"), name="cards"),
    path('tables/', TemplateView.as_view(template_name="to_remove/tables.html"), name="tables"),
    path('charts/', TemplateView.as_view(template_name="to_remove/charts.html"), name="charts"),
    path('animation/', TemplateView.as_view(template_name="to_remove/utilities-animation.html"), name="animation"),
    path('border/', TemplateView.as_view(template_name="to_remove/utilities-border.html"), name="border"),
    path('color/', TemplateView.as_view(template_name="to_remove/utilities-color.html"), name="color"),
    path('other/', TemplateView.as_view(template_name="to_remove/utilities-other.html"), name="other"),
]


if settings.DEBUG == True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

my_krzyzak21/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager
# Create your models here.


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset()\
            .filter(status="published")


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'))

    title = models.CharField(max_length=150)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')

    # Managers
    objects = models.Manager()
    published = PublishedManager()
    tags = TaggableManager()

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[
            self.publish.year,
            self.publish.strftime('%m'),
            self.publish.strftime('%d'),
            self.slug
        ])

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return f'Komentarz dodany przez {self.name} dla posta {self.post}'

my_krzyzak21/blog/forms.py
from django import forms
from .models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'body']


class SearchForm(forms.Form):
    query = forms.CharField()

my_krzyzak21/blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, Comment
from .forms import CommentForm, EmailPostForm, SearchForm
from django.views import View
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from django.core.mail import send_mail
from taggit.models import Tag
from django.db.models import Count
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank
# Create your views here.


def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False
    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = '{} ({}) zacheca do przeczytania "{}" '.format(cd['name'], cd['email'], post.title)
            message = 'Przeczytaj post "{}" na stronie {}\n\n Komentarz dodany przez {}: {} '.format(
                post.title, post_url, cd['name'], cd['comments'])
            send_mail(subject, message, 'krzyzak21.space@gmail.com', [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    context = {
        'form': form,
        'post': post,
        'sent': sent
    }
    return render(request, 'share.html', context)


# this same class like PostList
class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'list.html'


def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])
    paginator = Paginator(object_list, 3)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    context = {
        'page': page,
        'posts': posts,
        'tag': tag,
    }
    return render(request, 'list.html', context)


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post, status='published', publish__year=year,
                             publish__month=month, publish__day=day)
    comments = post.comments.filter(active=True)
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids)\
        .exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags'))\
        .order_by('-same_tags', '-publish')[:4]
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
            return redirect(post.get_absolute_url())
    else:
        comment_form = CommentForm()
    context = {
        'post': post,
        'comments': comments,
        'comment_form': comment_form,
        'similar_posts': similar_posts,
    }
    return render(request, 'detail.html', context)


def post_search(request):
    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            # results = Post.objects.annotate(search=SearchVector('title', 'body'),).filter(search=query)
            search_vector = SearchVector('title', 'body', 'tags')
            search_query = SearchQuery(query)
            results = Post.objects.annotate(
                search=search_vector, rank=SearchRank(search_vector, search_query)).filter(
                search=search_query).order_by('-rank')
    context = {
        'form': form,
        'query': query,
        'results': results
    }
    return render(request, 'search.html', context)

my_krzyzak21/blog/templates/detail.html
{% extends "base.html" %} {% block title %}{{ post.title }} {% endblock title %} {% block Pages %}{% load static %}{% load blog_tags %}
<h1 class="d-flex justify-content-center align-items-center">{{ post.title }}</h1>

<p class="date">Opublikowany {{ post.publish }} przez {{ post.author }}</p>
{% comment %} {{ post.body|linebreaks }} {% endcomment %} {{ post.body|markdown }}
<p>
    <a href="{% url 'blog:post_share' post.id %}"> Udostepnij post</a>
</p>

<h2>Podobne posty</h2>
{% for post in similar_posts %}
<p>
    <a href="{{ post.get_absolute_url }}"> {{ post.title }}</a>
</p>
{% empty %} Nie ma podobnych postów. {% endfor %} {% with comments.count as total_comments %}
<h2>{{ total_comments }} komentarz{{ total_comments|pluralize:"y" }}</h2>
{% endwith %} {% for comment in comments %}
<div class="comment">
    <p class="info">Komentarz {{ forloop.counter }} dodany przez {{ comment.name }} {{ comment.created }}</p>
    {{ comment.body|markdown }}
</div>
{% empty %}
<p>Nie ma żadnych komentarzy.</p>
{% endfor %} {% if new_comment %}
<h2>Twój komentarz został dodany</h2>
{% else %}
<h2>Dodaj nowy komentarz</h2>
<form action="." method="post">
    {{ comment_form.as_p }} {% csrf_token %}
    <p><input type="submit" value="Dodaj komentarz" /></p>
</form>
{% endif %} {% endblock Pages %}

my_krzyzak21/blog/templates/latest_posts.html
{% load blog_tags %}
<ul>
    {% for post in latest_posts %}
    <li>
        <a href="{{ post.get_absolute_url }}"> {{ post.title }}</a>
    </li>
    {% endfor %}
</ul>

<h3>Najczęściej komentowane posty</h3>
{% get_most_commented_posts as most_commented_posts %}
<ul>
    {% for post in most_commented_posts %}
    <li>
        <a href="{{ post.get_absolute_url }}"> {{ post.title }}</a>
    </li>
    {% endfor %}
</ul>

my_krzyzak21/blog/templates/list.html
{% extends "base.html" %} {% block title %}Mój blog {% endblock title %} {% block Pages %}{% load static %}{% load blog_tags %}
<div class="content">
<div class="d-sm-flex justify-content-md-end aligh-items-center mb-4">
    <div class='col-xl-3 col-md-6 mb-4'>
        <div class='card border-left-info shadow h-100 py-2'>
            <div class='card-body'>
            <div class="row no-gutters d-flex align-items-center justify-content-center">
                <div class="">
                        <a href="{% url "blog:post_feed" %}">Subskrybuj RSS</a>
                        <p>ilośc postów {% total_posts %}</p>
                        <h3>Najnowsze posty</h3>
                        {% show_latest_posts 3 %}
                </div>
            </div>
            </div>
        </div>
    </div>
</div>
<div id="sidebar">
    <h1 class="d-flex justify-content-center align-items-center">Mój blog</h1>
    <p> Obecna ilość opublikowanych blogów: {% total_posts %}</p>
<h3>Najnowsze posty</h3>
{% show_latest_posts 3 %}
</div>

    {% if tag %}
    <h2>Posty oznaczone tagiem "{{ tag.name }}"</h2>
    {% endif %}


    {% for post in posts %}
    <h2>
        <a href="{{ post.get_absolute_url }}"> {{ post.title }} </a>
    </h2>

    <p class="tagi"> Tagi:
        {% for tag in post.tags.all %}
        <a href="{% url 'blog:post_list_by_tag' tag.slug %}">{{ tag.name }}</a>
    {% comment %} <p class="tags">Tagi: {{ post.tags.all|join:", " }}</p> {% endcomment %}
    {% if not forloop.last %}, {% endif %}
    {% endfor %}
    </p>



    <p class="date">Opublikowany: {{ post.publish }} przez {{ post.author }}</p>
    {{ post.body|markdown|truncatewords_html:30 }}
    {% comment %} {{ post.body|linebreaks|truncatewords:30 }} {% endcomment %}
    {% endfor %}
</div>
{% block content %}
<p>{% include "pagination.html" with page=posts %}</p>
{% comment %}
<p>{% include "pagination.html" with page=page_obj %}</p>
{% endcomment %} {% endblock content %} {% endblock Pages %}

my_krzyzak21/blog/templates/pagination.html
{% load static %}
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
        <a href="?page={{ page.previous_page_number }}">Poprzednia</a>
        {% endif %}
        <span class="current"> Strona {{ page.number }} z {{ page.paginator.num_pages }}. </span>
        {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}">Następna</a>
        {% endif %}
    </span>
</div>

my_krzyzak21/blog/templates/search.html
{% extends "base.html" %} {% block title %}Szukaj {% endblock title %}{% load static %}{% block Pages %} {% block content %}{% load blog_tags %}

{% if query %}
<h1>posty zawierające {{ query }}</h1>
{% with results.count as total_results %}
<h3>Znaleziono {{ total_results }} wynik{{ total_results|pluralize:"i " }}</h3>
{% endwith %}
{% for post in results %}
<h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</h4>
{{ post.body|markdown|truncatewords_html:5 }}
{% empty %}
<p>Brak wyników zapytania</p>
{% endfor %}
<p><a href="{% url "blog:post_search" %}">Szukaj ponownie</a></p>
{% else %}
<h1>Szukaj postów</h1>
<form method="get">
{{ form.as_p }}
<input type="submit" value="Szukaj">
</form>
{% endif %}

{% endblock content %} {% endblock Pages %}

my_krzyzak21/blog/templates/share.html
{% extends "base.html" %} {% block title %}Udostepnij post {% endblock title %}{% load static %}
{% block Pages %}

{% block content %}
{% if sent %}
<h1> Wiadomość email wysłana</h1>
<p> Wysłanie posta "{{ post.title }}" do {{ form.cleaned_data.to }} zakończyło się sukcesem. </p>
{% else %}
<h1>Udostepnij posta "{{ post.title}}" przez email </h1>
<form action="." method="POST" class="d-flex flex-column">
{% for field in form %}
<div class="justify-content-start align-items-center">
{{ field.errors }}
<div>
{{ field.label_tag }}</div> {{ field }}
</div>
{% endfor %}
{% csrf_token %}
<input type="submit" value="Wyślij wiadomość email">
</form>
{% endif %}
{% endblock content %}

{% endblock Pages %}