my_gless/articles/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('<int:article_id>/', views.LoadArticle.as_view(), name='article-id'),
    path('all/', views.LoadAllArticles.as_view()),
    path('create/', views.CreateArticle.as_view(), name='article-create'),
]

my_gless/my_gless/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('profile/', include('auth_users.urls'), name='profile'),
    path('', include('home_loader.urls'), name='base'),
    path('articles/', include('articles.urls'), name='articles'),
    url('social/', include('social_django.urls', namespace='social')),
    path("password-reset/", auth_views.PasswordResetView.as_view(template_name="password_reset.html"), name="password_reset"),
    path("password-reset/done/", auth_views.PasswordResetDoneView.as_view(template_name="password_reset_done.html"), name="password_reset_done"),
    path("password-reset-confirm/<uidb64>/<token>", auth_views.PasswordResetConfirmView.as_view(template_name="password_reset_confirm.html"), name="password_reset_confirm"),
    path("password-reset-complete/", auth_views.PasswordResetCompleteView.as_view(template_name="password_reset_complete.html"), name="password_reset_complete"),

]


# Do ładowania zdjęć w trybie DEBUG oraz CSS
if settings.DEBUG == True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

my_gless/articles/models.py
from django.db import models
from django.conf import settings
from datetime import datetime
from django.contrib.auth.models import User
from mptt.models import MPTTModel, TreeForeignKey
from django.utils import timezone
from django.contrib.auth import get_user_model
# Create your models here.


class Article(models.Model):
    class ArticleManager(models.Manager):
        def get_queryset(self):
            return super().get_queryset().filter(status='published')

    options = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=149, verbose_name='Title of Article')
    content = models.TextField(verbose_name='Content of Article')
    pub_date = models.DateTimeField(verbose_name='Date', default=datetime.now, editable=False)
    article_image = models.ImageField(upload_to='image', verbose_name='Image of Article', null=True, blank=True)
    article_author = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    status = models.CharField(max_length=10, choices=options, default='published')
    objects = models.Manager()  # default manager
    articlemanager = ArticleManager()  # custom manager

    class MPTTMeta:
        order_by = ('-publish')

        def __str__(self):
            return self.title


class Comment(MPTTModel):
    post = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default=1)
    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children')
    content = models.TextField()
    publish = models.DateTimeField(auto_now_add=True)
    status = models.BooleanField(default=True)

    class MPTTMeta:
        order_insertion_by = ['publish']

    def __str__(self):
        return self.content

my_gless/articles/forms.py
from django import forms
from django.forms.widgets import DateTimeInput, Textarea
from .models import Article, Comment
from datetime import date, datetime
from mptt.forms import TreeNodeChoiceField
from django.contrib.auth.models import User


class ArticleModelForm(forms.ModelForm):  # widok tworzenia lub aktualizacji formularza
    class Meta:
        model = Article
        now = datetime.now()
        current_time = now.strftime("%H:%M")
        fields = ['title', 'content', 'article_image']
        widgets = {
            'pub_date': DateTimeInput(
                attrs={
                    'template_name': 'django/forms/widgets/datetime.html',
                    'type': 'datetime-local',
                    'min': f"{date.today()}T{current_time}",
                    'max': f"{date.today()}T{current_time}",
                }),
            'content': Textarea(
                attrs={
                    'template_name': 'django/forms/widgets/textarea.html',
                    'rows': 10,
                    'width': '100%',
                    'cols': '100%',
                    'style': 'width: 100%;',
                }
            ),
        }


class NewCommentForm(forms.ModelForm):
    parent = TreeNodeChoiceField(queryset=Comment.objects.all())

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['parent'].widget.attrs.update(
            {'class': 'd-none'})
        self.fields['parent'].label = ''
        self.fields['parent'].required = False

    class Meta:
        model = Comment
        model2 = Article
        fields = ('content', 'parent')

        widgets = {
            'content': forms.Textarea(attrs={
                'class': 'form-control',
                'style': 'width: 98%; margin: auto; padding: 5px; align-items: center;',
                'rows': 10,
            }),
        }

    def save(self, *args, **kwargs):
        Comment.objects.rebuild()
        return super(NewCommentForm, self).save(*args, **kwargs)

my_gless/articles/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from articles.models import Article
from django.views import View
from django.core.paginator import Paginator
from auth_users.models import Register
from django.contrib.auth.models import User
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views.generic import (
    CreateView,
    UpdateView,
    DeleteView
)
from .models import Article, Comment
from .forms import ArticleModelForm, NewCommentForm
from django.views.generic import ListView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from social_django.models import UserSocialAuth
# Create your views here.


class LoadArticle(View):

    def get(self, request, article_id):

        post = get_object_or_404(Article, id=article_id, status='published')
        allcomments = post.comments.filter(status=True)
        page = request.GET.get('page', 1)

        paginator = Paginator(allcomments, 10)
        try:
            comments = paginator.page(page)
        except PageNotAnInteger:
            comments = paginator.page(1)
        except EmptyPage:
            comments = paginator.page(paginator.num_pages)

        else:
            comment_form = NewCommentForm()
            context = {
                'article': Article.objects.get(id=article_id),
                'post': post, 'comments': comments, 'comment_form': comment_form, 'allcomments': allcomments,
                'auth_social_users_fb': UserSocialAuth.objects.filter(provider='facebook').values_list(
                    'user_id', flat=True),
                'auth_social_users_git': UserSocialAuth.objects.filter(provider='github').values_list(
                    'user_id', flat=True),
                'auth_social_users_uid': UserSocialAuth.objects.filter().values_list(
                    'uid', flat=True)
            }
        return render(request, 'article.html', context)

    def post(self, request, article_id):
        post = get_object_or_404(Article, id=article_id, status='published')
        user_comment = None
        if request.method == 'POST':
            comment_form = NewCommentForm(request.POST)
            if comment_form.is_valid():
                user_comment = comment_form.save(commit=False)
                user_comment.post = post
                user_comment.user = request.user
                user_comment.save()
                return HttpResponseRedirect('../' + str(article_id))


class CreateArticle(View):
    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            form_class = ArticleModelForm(request.POST, request.FILES)
            context = {
                'form_class': form_class,
            }
            return render(request, 'create_article.html', context)
        else:
            return redirect('/')

    def post(self, request):
        if request.method == 'POST':
            if request.user.is_authenticated:
                form_class = ArticleModelForm(request.POST, request.FILES)
                if form_class.is_valid():
                    form_class.instance.article_author_id = request.user.id
                    form_class.save()
                context = {
                    'form_class': form_class,
                }
                return redirect('base')
            else:
                return HttpResponse('Page dont exist please login')


class LoadAllArticles(View):

    def get(self, request):
        context = {
            'articles_all': Article.objects.all()[::-1],
        }
        return render(request, 'articles_all.html', context)

my_gless/articles/templates/article.html
{% extends "base.html" %} {% block article %} {% load static %}
<style>
.article-box section {
    padding: 20px;
    padding-top: 10px;
    margin-right: 10px;
}
@media screen and (max-width: 700px) {

    .content {
        font-size: 11px;
    }
}
</style>
<div class="article-bar">
    <div><h1>{{ article.title }}</h1></div>
    <div><h2>Created by: {{ article.article_author }} in {{ article.pub_date }}</h2></div>
</div>
<div class="article-box" style="min-height:300px;">
    <section>
        {% if article.article_image %}
        <img src="{{ article.article_image.url }}" alt="image 1" align="left" />
        {% else %} {% endif %}
        <span>{{ article.content }} </span>
    </section>
</div>

<div class="article-bar">
{% with allcomments.count as total_comments %}
<div><h1>Number of comments: {{ total_comments }}</h1></div>
{% endwith %}
</div>


{% load mptt_tags %}
<div>
{% recursetree comments %}
<style>
.parent {
    margin: 5px;
}
.children {
    margin-left: 30px;
}
.content {
    border: 1px solid black;
    border-bottom-left-radius: 20px;
    border-bottom-right-radius: 20px;
    padding: 15px;
    min-height: 50px;
}
.btn1 {
    float: right;
    margin-bottom: 10px;
    border-radius: 5px;
    width: 100px;
    background-color: rgba(70, 133, 54, 0.542);
    color: white;
}
.article-bar2 {
    background-color: var(--green5);
    width: 100%;
    min-height: 45px;
    border-top-left-radius: 20px;
    border-top-right-radius: 20px;
    display: flex;
    flex-wrap: wrap;
    justify-content: space-between;
}
.article-bar2 .home-bar {
    padding: 5px;
    margin-left: 20px;

}
.article-bar2 div {
    display: flex;

}
.article-bar2 h1 {
    font-family: Arial, "Liberation Sans", "Droid Sans", Tahoma, "Lucida Sans", "Lucida Sans Unicode", "Lucida Grande", "Trebuchet MS", Verdana, Helvetica, sans-serif;
    font-size: 13px;
    font-weight: 400;
    text-shadow: 1px 1px 1px var(--dark);
    font-style: italic;
    color: var(--white-background);
    text-align: center;
    padding: 10px;
}
.article-bar2 div h2 {
    margin-top: 15px;
    text-align: right;
    margin-right: 15px;
    font-family: Arial, "Liberation Sans", "Droid Sans", Tahoma, "Lucida Sans", "Lucida Sans Unicode", "Lucida Grande", "Trebuchet MS", Verdana, Helvetica, sans-serif;
    font-size: 10px;
    font-weight: 400;
    text-shadow: 1px 1px 1px var(--dark);
    font-style: italic;
    color: var(--white-background);
}
</style>
<div id="{{ node.id }}" class="parent">
    <div class="article-bar2">
        <div class="home-bar">
            {% for obj in register_all %}
                {% if node.user_id == obj.user_id %}
                <img
                    src="{{ obj.image_add.url }}"
                    alt="user-image"
                    class="user-class"
                />
                {% endif %}
            {% endfor %}
            {% for fb_id in auth_social_users_fb %}
            {% if node.user_id == fb_id %}
                    {% for uid in auth_social_users_uid %}
                    {% if uid|length == 16 %}
                    <img
                    src="https://graph.facebook.com/{{uid}}/picture"
                    alt="user-image"
                    class="user-class"
                    />
                    {% endif %}
                    {% endfor %}
            {% else %}
            {% endif %}
            {% endfor %}
            {% for git_id in auth_social_users_git %}
            {% if node.user_id == git_id %}
                    {% for uid in auth_social_users_uid %}
                    {% if uid|length == 8 %}
                    <img
                    src="https://avatars.githubusercontent.com/u/{{uid}}?s=60&v=4"
                    alt="user-image"
                    class="user-class"
                    />
                    {% endif %}
                    {% endfor %}
            {% else %}
            {% endif %}
            {% endfor %}
        <h1>{{ node.user }}</h1>
        </div>
        <div>
            <div><h2>{{ node.publish }}</h2></div>
        </div>
    </div>
    <div class="content">
        <div>{{ node.content }}</div>
        <div class='btn-padder'>
            {% if node.level < 20 %}
            {% if user.is_authenticated %}
            <button class="btn1" onclick="myFunction({{ node.id }})">Reply</button>
            {% else %}
            {% endif %}
            {% endif %}
        </div>
    </div>
</div>
{% if not node.is_leaf_node %}
<div class="children">
    {{ children }}
</div>
{% endif %}
{% endrecursetree %}
</div>
<style>
#myForm {
    padding: 10px;
}
.btn-form {
    float: right;
    margin-bottom: 10px;
    border-radius: 5px;
    width: 100px;
    background-color: rgba(70, 133, 54, 0.542);
    color: white;
}
.btn-padder {
    padding: 10px;
}
</style>
{% if user.is_authenticated %}
<form id="myForm" method="post">
<div class="article-bar">
<div><h1>Create new comment</h1></div>
</div>
{% csrf_token %}
{{ comment_form.content }}
<div class='btn-padder'>
<button type="submit" class="btn-form">Submit</button>
</div>
</form>
{% else %}
{% endif %}

<script>
  function formExit() {
    document.getElementById("newForm").remove();
  }

  function myFunction(id) {
    if (document.contains(document.getElementById("newForm"))) {
      document.getElementById("newForm").remove();
    }

    var d1 = document.getElementById(id);
    d1.insertAdjacentHTML('afterend',

    '<form id="newForm" class="form-insert py-2" method="post"> \
            <select hidden name="parent" class="d-none" id="id_parent"> \
                <option value="' + id + '" selected="' + id + '"></option> \
            </select> \
            <div style="padding: 5px; width: 300px; float: right; border-bottom-left-radius: 20px; border-bottom-right-radius: 20px;"> \
            <div class="article-bar"><div><h1>Reply: </h1></div></div> \
            <textarea name="content" cols="40" rows="5" class="form-control" required id="id_content"></textarea> \
            {% csrf_token %} \
            <div class="btn-padder"> \
            <button type="submit" class="btn-form">Submit</button> \
            <button type="button" class="btn-form" onclick="formExit()"">Close</button></div></div> \
            </div> \
            </div> \
    </form>'
    );
    //document.querySelector('#id_parentt [value="' + id + '"]').selected = true;
  }

  $('#myForm').trigger("reset");
</script>
<br>
<style>
.article-page-nav {
    background-color: var(--green5);
    width: 100%;
    min-height: 45px;
    border-radius: 20px;
    margin-bottom: 10px;
    text-align: center;
    display: flex;
    justify-content: center;
    align-items: center;
}
.article-page-nav li {
    justify-content: space-between;
}
.article-page-nav a {
    font-family: Arial, "Liberation Sans", "Droid Sans", Tahoma, "Lucida Sans", "Lucida Sans Unicode", "Lucida Grande", "Trebuchet MS", Verdana, Helvetica, sans-serif;
    font-style: italic;
    color: white;
}
</style>
<div class="article-page-nav" id="pagenav">
          {% if comments.has_other_pages %}
          <ul class="pagination">
            {% if comments.has_previous %}
            <li class="page-item"><a class="page-link" href="?page={{ comments.previous_page_number }}">Previous</a>
            </li>
            {% else %}
            <li class="page-item disabled"><a class="page-link" href="#pagenav">Previous</a></li>
            {% endif %}
            {% for num in comments.paginator.page_range %}
            {% if comments.number == l %}
            <li class="page-item active"><span class="page-link">{{ num }} <span class="sr-only">(current)</span></span>
            </li>
            {% else %}
            <li><a class="page-link" href="?page={{ num }}#pagenav">{{ num }}</a></li>
            {% endif %}
            {% endfor %}
            {% if comments.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ comments.next_page_number }}">Next</a></li>
            {% else %}
            <li class="page-item disabled"><a class="page-link" href="#pagenav">Next</a></li>
            {% endif %}
          </ul>
          {% endif %}
</div>
{% endblock article %}

my_gless/articles/templates/articles.html
{% extends "base.html" %} {% block articles %} {% load static %} {% for ten_articles in page_obj %}
<div class="article-bar">
    <div><h1>{{ ten_articles.title }}</h1></div>
    <div><h2>{{ ten_articles.pub_date }}</h2></div>
</div>
<div class="article-box">
    <section>
        {% if ten_articles.article_image %}
        <img src="{{ ten_articles.article_image.url }}" alt="image 1" align="left" />
        {% else %} {% endif %}
        <span>{{ ten_articles.content|truncatewords:100}}</span>
        <div>
            <a href="/articles/{{ ten_articles.id }}/"><button>Czytaj więcej</button></a>
        </div>
    </section>
</div>
{% endfor %} {% endblock articles %}

my_gless/articles/templates/articles_all.html
{% extends "base.html" %} {% block articles_allone %} {% load static %}{% for all in articles_all %}
<div class="article-bar">
    <div><h1>{{ all.title }}</h1></div>
    <div><h2>{{ all.pub_date }}</h2></div>
</div>
<div class="article-box">
    <section>
        {% if all.article_image %}
        <img src="{{ all.article_image.url }}" alt="image 1" align="left" />
        {% else %} {% endif %}
        <span>{{ all.content }} </span>
    </section>
</div>
{% endfor %} {% endblock articles_allone %}

my_gless/articles/templates/create_article.html
{% extends "base.html" %} {% block article %} {% load static %}
<style>
.scrollable {
    width:100%;
    min-height: 400px;
}
.scrollable div {
    margin: 5px;
}
.lay {
    padding: 20px;
}
.add_article {
    margin: 0 auto;
    background-color: #2e5c54;;
    padding: 20px;
    border-radius: 20px;
}
.add_article div {
    margin-top: 5px;
    margin-bottom: 5px;
}
.log-txt {
    text-align: left;
    padding-bottom: 5px;
    padding-top: 5px;
    font-family: Arial, "Liberation Sans", "Droid Sans", Tahoma, "Lucida Sans", "Lucida Sans Unicode", "Lucida Grande", "Trebuchet MS", Verdana, Helvetica, sans-serif;
    font-size: 13px;
    font-weight: 400;
    text-shadow: 1px 1px 1px var(--dark);
    font-style: italic;
    color: var(--white-background);
}
.user-article-add {
    padding-bottom: 5px;
    padding-top: 5px;
    font-family: Arial, "Liberation Sans", "Droid Sans", Tahoma, "Lucida Sans", "Lucida Sans Unicode", "Lucida Grande", "Trebuchet MS", Verdana, Helvetica, sans-serif;
    font-size: 13px;
    font-weight: 400;
    text-shadow: 1px 1px 1px var(--dark);
    font-style: italic;
    color: var(--white-background);
    line-height: 1rem;
}
@media screen and (max-width: 700px) {

    .scrollable {
    width:100%;
    }
    .scrollable div {
        margin: auto;
    }

    .add_article {
        width: 90%;
    }
    .lay {
    padding: 5px;
        width: 80%;
    }
}
</style>
<div class="lay">
    <div class="add_article">
        {% if user.is_authenticated %}
        <form action='.' method='POST' enctype="multipart/form-data">{% csrf_token %}
        <div class="log-txt">{{ form_class.title.label }}</div>
        <div>{{ form_class.title }}</div>
        <div class="log-txt">{{ form_class.content.label }}</div>
        <div class='content'>{{ form_class.content }}</div>
        <div>{{ form_class.status }}</div>
        <div class="user-article-add">Adding by: {{ user }}</div>
        <div class="log-txt">{{ form_class.article_image.label }}</div>
        <div class="log-btn"style="background-color: #8d5555;" >{{ form_class.article_image }}</div>
            <input class="log-btn" type='submit' value='Save' />
        </form>
        {% else %}
        <p style="padding: 20px;">You cant add articles please login</p>
        {% endif %}
    </div>
</div>
{% endblock article %}