my_gless/articles/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('<int:article_id>/', views.LoadArticle.as_view(), name='article-id'),
    path('all/', views.LoadAllArticles.as_view()),
    path('create/', views.CreateArticle.as_view(), name='article-create'),
]

my_gless/auth_users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('register/', views.RegisterPageView.as_view(), name='register'),
    path('register/confirm/', views.RegisterConfirm.as_view(), name='register-confirm'),
    path('register/login/', views.RegisterLog.as_view(), name='register-log'),
    path('login/', views.LoginPageView.as_view(), name='login'),
    path('logout/', views.LogoutPageView.as_view(), name='logout'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
]

my_gless/my_gless/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('profile/', include('auth_users.urls'), name='profile'),
    path('', include('home_loader.urls'), name='base'),
    path('articles/', include('articles.urls'), name='articles'),
    url('social/', include('social_django.urls', namespace='social')),
    path("password-reset/", auth_views.PasswordResetView.as_view(template_name="password_reset.html"), name="password_reset"),
    path("password-reset/done/", auth_views.PasswordResetDoneView.as_view(template_name="password_reset_done.html"), name="password_reset_done"),
    path("password-reset-confirm/<uidb64>/<token>", auth_views.PasswordResetConfirmView.as_view(template_name="password_reset_confirm.html"), name="password_reset_confirm"),
    path("password-reset-complete/", auth_views.PasswordResetCompleteView.as_view(template_name="password_reset_complete.html"), name="password_reset_complete"),

]


# Do ładowania zdjęć w trybie DEBUG oraz CSS
if settings.DEBUG == True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

my_gless/auth_users/models.py
from django.db import models
from django.contrib.auth.models import User
from .validators import validate_image, no_future_date


class Register(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date_of_birth = models.DateField(
        max_length=8, verbose_name="date of birth", validators=[no_future_date])
    image_add = models.ImageField(
        upload_to="avatars", verbose_name="avatar", validators=[validate_image])

    def __str__(self):
        return self.user.username

my_gless/auth_users/forms.py
from django import forms
from django.forms.widgets import DateInput
from django.forms import ModelForm
from .models import Register
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from datetime import date
from dateutil.relativedelta import relativedelta


class RegisterForm(ModelForm):
    class Meta:
        model = Register
        fields = ['date_of_birth', 'image_add']
        widgets = {
            'date_of_birth': DateInput(
                attrs={
                    'class': 'datepicker',
                    'type': 'date',
                    'min': "1914-05-11",
                    'max': date.today() - relativedelta(years=18),
                })
        }


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

my_gless/auth_users/views.py
from requests import request, HTTPError
from django.shortcuts import render, redirect
from django.views import View
from django.http import HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.template.context_processors import csrf
from django.contrib.auth.models import User
from auth_users.forms import RegisterForm, CreateUserForm
from django.contrib import messages
from django.core.paginator import Paginator
from articles.models import Article
from auth_users.models import Register
from django.views.generic import TemplateView

from django.contrib.auth.tokens import default_token_generator
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from django.core.mail import EmailMessage
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.contrib.auth import get_user_model

from email.mime.image import MIMEImage

UserModel = get_user_model()


class LoginPageView(View):
    def get(self, request):
        return render(request, 'login.html')

    def post(self, request):
        context = {
            'data': request.POST,
            'has_error': False
        }
        username = request.POST.get('username')
        password = request.POST.get('password')
        if username == '':
            messages.add_message(request, messages.ERROR,
                                 'Username is required')
            context['has_error'] = True
        if password == '':
            messages.add_message(request, messages.ERROR,
                                 'Password is required')
            context['has_error'] = True
        user = authenticate(request, username=username, password=password)

        if not user and not context['has_error']:
            messages.add_message(request, messages.ERROR, 'Invalid login')
            context['has_error'] = True

        if context['has_error']:
            return render(request, 'login.html', status=401, context=context)
        login(request, user)
        return redirect('/')


class LogoutPageView(View):
    def get(self, request):
        logout(request)
        return redirect('/')


class RegisterConfirm(View):

    def get(self, request):
        return render(request, 'reg_conf.html', {})


class RegisterLog(View):

    def get(self, request):
        return render(request, 'reg_log.html', {})


class RegisterPageView(View):
    template_name = 'register.html'

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('/')
        else:
            user_form = CreateUserForm(request.POST)
            register_form = RegisterForm(request.POST)
        context = {'user_form': user_form, 'register_form': register_form}
        return render(request, self.template_name, context)

    def post(self, request):
        if request.method == 'POST':
            user_form = CreateUserForm(request.POST)
            register_form = RegisterForm(request.POST, request.FILES)
            if user_form.is_valid():
                user = user_form.save(commit=False)
                user.is_active = False
                user.save()
                user_form_id = user_form.instance.id
                register_form.instance.user_id = user_form_id
                if register_form.is_valid():
                    register_form.save()
                    current_site = get_current_site(request)
                    mail_subject = 'Activate your account.'
                    username = user_form.cleaned_data.get('username')
                    message = render_to_string('active_email.html', {
                        'user': user,
                        'domain': current_site.domain,
                        'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                        'token': default_token_generator.make_token(user),
                    })
                    to_email = user_form.cleaned_data.get('email')
                    image_data = open('static/img/LOGO150x40.png', 'rb').read()
                    image = MIMEImage(image_data, 'png')
                    image.add_header('Content-ID', '<embed_image>')
                    email = EmailMessage(mail_subject, message, to=[to_email])
                    email.attach(image)
                    email.content_subtype = "html"
                    email.mixed_subtype = 'related'
                    email.send()
                    return redirect('register-confirm')
            else:
                print(f"Error like: {user_form.errors}")
                print(f"Error like: {register_form.errors}")
        else:
            context = {'user_form': user_form, 'register_form': register_form}
            return render(request, self.template_name, context)


def activate(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = UserModel._default_manager.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and default_token_generator.check_token(user, token):
        user.is_active = True
        user.save()
        return redirect('register-log')
    else:
        return HttpResponse('Activation link is invalid!')

my_gless/auth_users/templates/active_email.html
<center>
<div>
<img src="cid:embed_image"/>
</div>
{% autoescape off %}{% load static %}
</br>
<div>
<b>Hi {{ user.username }},</b>
</br>
</div>
<p>Please click on the link to confirm your registration,</p>
http://{{ domain }}{% url 'activate' uidb64=uid token=token %}
<p>If you think, it's not you, then just ignore this email.</p>
{% endautoescape %}
</center>

my_gless/auth_users/templates/login.html
{% extends "base.html" %}{% block login %}{% load static %}
{% if user.is_authenticated %}
<center style="padding: 20px">You are logedin</center>
{% else %}
<style>
.form-a {
    width: 300px;
    margin: 0 auto;
    text-align: center;
    background-color: rgba(70, 133, 54, 0.816);
    padding: 20px;
    border-radius: 20px;
}
</style>
<form method="POST" style="margin: 30px;">
    <div class="form-a">
        {% csrf_token %} {{ form.as_p }}
        <div class="log-text">
            <label for="log-log" class="log-txt">Login</label>
            <input type="text" name="username" class="log-name log-docker" placeholder="Login lub E-mail" />
        </div>
        <div class="log-text">
            <span class="log-txt">Hasło</span>
            <input type="password" name="password" class="log-pass log-docker" placeholder="Hasło" />
        </div>
        <fieldset class="log-button">
            <p>
                <input type="submit" class="log-btn" value="Zaloguj się" />
            </p>
        </fieldset>
        <li class="log-or">
            <span class="">lub</span>
        </li>
        <li class="fb-btn">
            <a class="log-fb" href="{% url 'social:begin' 'facebook' %}"><i class="fab fa-facebook-square"></i> <span>Zaloguj przez Facebook</span></a>
        </li>
        <li class="google-btn" style="background-color: black">
            <a class="log-google" href="{% url 'social:begin' 'github' %}"><i class="fab fa-github"></i> <span>Zaloguj przez Google</span></a>
        </li>
        <li>
            <a id="register" style="color: red; font-size: 15px;" class="register" href="/profile/register" title="Zarejestruj się"><span>Nie masz konta?</span> Zarejestruj się.</a>
        </li>
    </div>
</form>
{% endif %}
{% endblock login %} {% for message in messages %} {{message}}{% endfor %}

my_gless/auth_users/templates/reg_conf.html
{% extends "base.html" %}{% block register_confirm %}{% load static %}
<center style="padding: 20px;">
<p>Please confirm your email address to complete the registration.</p>
<br>
<p>if your email didn't pass, try register again.</p>
<a id="login" class="register" style="font-size: 20px; color: red;" href="{% url 'register' %}" title="Click to login"><span></span>Click to register</a>
</center>
{% endblock register_confirm %}

my_gless/auth_users/templates/reg_log.html
{% extends "base.html" %}{% block register_confirm %}{% load static %}
<center style="padding: 20px;">
<p>Thank you for your email confirmation. Now you can login your account.</p>

<a id="login" class="register" style="font-size: 20px; color: red;" href="{% url 'login' %}" title="Click to login"><span></span>Click to login</a>
</center>
{% endblock register_confirm %}

my_gless/auth_users/templates/register.html
{% comment %} {% extends "base.html" %} {% endcomment %}
{% block register %}{% load static %}

{% comment %} <form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <h1>{{ user_form.username.label }}{{ user_form.username }}</h1>
    <h1>{{ user_form.email.label }}{{ user_form.email }}</h1>
    <h1>{{ user_form.password1.label }}{{ user_form.password1 }}</h1>
    <h1>{{ user_form.password2.label }}{{ user_form.password2 }}</h1>

    <h1>{{ register_form.date_of_birth.label }}{{ register_form.date_of_birth }}</h1>
    <h1>{{ register_form.image_add.label }}{{ register_form.image_add }}</h1>
    <input type="submit" value="Register" />
</form>
<div class="d-flex justify-content-center links">Already have an account? <a href="{% url 'login' %}" class="ml-2">Login</a></div>
{% for message in messages %}{{message}} {% endfor %}
<br />

{% if user_form.errors %}
    {% for field in user_form %}
        {% for error in field.errors %}
            <p>{{ error|escape }}</p>
        {% endfor %}
    {% endfor %}
{% endif %}
{% if register_form.errors %}
    {% for field in register_form %}
        {% for error in field.errors %}
            <p>{{ error|escape }}</p>
        {% endfor %}
    {% endfor %}
{% endif %}
{% endblock register %} {% endcomment %}


<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/all.css">

<style type="text/css">
.container {
    padding:5px;
}
.card-body {
    background-color: rgba(70, 133, 54, 0.816);
    color: white;
    border-radius: 20px;
}
.divider-text {
    position: relative;
    text-align: center;
    margin-top: 15px;
    margin-bottom: 15px;
}
.divider-text span {
    padding: 7px;
    font-size: 12px;
    position: relative;
    z-index: 2;
}
.divider-text:after {
    content: "";
    position: absolute;
    width: 100%;
    border-bottom: 1px solid #ddd;
    top: 55%;
    left: 0;
    z-index: 1;
}

.btn-facebook {
    background-color: #405D9D;
    color: #fff;
}
.btn-github {
    background-color: black;
    color: #fff;
}
.btn-primary {
    background-color: black;
    color: #fff;
}
</style>
<div class="container">
<div class="card bg-light">
<article class="card-body mx-auto" style="max-width: 400px;">
	<h4 class="card-title mt-3 text-center">Create Account</h4>
	<p class="text-center">Get started with your free account</p>
	<p>
		<a href="{% url 'social:begin' 'github' %}" class="btn btn-block btn-github"> <i class="fab fa-github"></i>   Login via Github</a>
		<a href="{% url 'social:begin' 'facebook' %}" class="btn btn-block btn-facebook"> <i class="fab fa-facebook-f"></i>   Login via facebook</a>
	</p>
	<p class="divider-text">
        <span class=""></span>
    </p>
	<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
	<div class="form-group input-group">
		<div class="input-group-prepend">
		    <span class="input-group-text"> <i class="fa fa-user"></i> </span>
		 </div>
        <input name="username" class="form-control" placeholder="{{ user_form.username.label }}" type="text">
    </div> <!-- form-group// -->
    <div class="form-group input-group">
    	<div class="input-group-prepend">
		    <span class="input-group-text"> <i class="fa fa-envelope"></i> </span>
		 </div>
        <input name="email" class="form-control" placeholder="{{ user_form.email.label }}" type="email">
    </div> <!-- form-group// -->
    <div class="form-group input-group">
    	<div class="input-group-prepend">
		    <span class="input-group-text"> <i class="fa fa-lock"></i> </span>
		</div>
        <input name="password1" class="form-control" placeholder="{{ user_form.password1.label }}" type="password">
    </div> <!-- form-group// -->
    <div class="form-group input-group">
    	<div class="input-group-prepend">
		    <span class="input-group-text"> <i class="fa fa-lock"></i> </span>
		</div>
        <input name="password2" class="form-control" placeholder="{{ user_form.password2.label }}" type="password">
    </div> <!-- form-group// -->
        <div class="form-group" style="text-align: center; width: 100%;">
        {{ register_form.date_of_birth }}
    </div> <!-- form-group// -->
        <div class="form-group">
        <input type="file" name="image_add" accept="image/*" required=""  class="btn btn-primary btn-block" id="id_image_add">
    </div> <!-- form-group// -->
    <div class="form-group">
        <button type="submit" class="btn btn-primary btn-block" value="Register"> Create Account  </button>
    </div> <!-- form-group// -->
    <div>
    <p class="text-center">Have an account? <a style="color:red; font-size:24px;" href="{% url 'login' %}">Log In</a> </p>
    </div>
    <p class="text-center" style="font-size:1px">{% for message in messages %}{{message}} {% endfor %}
<br />

{% if user_form.errors %}
    {% for field in user_form %}
        {% for error in field.errors %}
            <p class="text-center" style="font-size:9px">{{ error|escape }}</p>
        {% endfor %}
    {% endfor %}
{% endif %}
{% if register_form.errors %}
    {% for field in register_form %}
        {% for error in field.errors %}
            <p class="text-center" style="font-size:9px">{{ error|escape }}</p>
        {% endfor %}
    {% endfor %}
{% endif %}</p>
    </form>
</article>
</div>
</div>
{% endblock register %}

my_gless/auth_users/templates/register_ask.html
{% extends "base.html" %}{% block register %}{% load static %}


Check for email {% user.username %}


{% endblock register %}

my_gless/auth_users/templates/register_confirm.html
{% extends "base.html" %}{% block register %}{% load static %}


Wellcome in website


{% endblock register %}